name: se7ety_123
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  gap: ^3.0.1
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.16
  lottie: ^3.2.0
  flutter_localization: ^0.2.3
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.0+3
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
