// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdq1iB-rHNEQeiTJ-VKU0_W0nELAfqCEQ',
    appId: '1:468049593524:web:f29cd408effc7620ff43e1',
    messagingSenderId: '468049593524',
    projectId: 'se7ety-a123',
    authDomain: 'se7ety-a123.firebaseapp.com',
    storageBucket: 'se7ety-a123.firebasestorage.app',
    measurementId: 'G-TY4LHLVJCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8OhHC7JEX3kYkSZTVeiASLnKIkKs_FhM',
    appId: '1:468049593524:android:d7545b30e00754dcff43e1',
    messagingSenderId: '468049593524',
    projectId: 'se7ety-a123',
    storageBucket: 'se7ety-a123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJc7gibHVMhyUi_RPdQvmSZA7snUD4jdw',
    appId: '1:468049593524:ios:603e6668cc3a35d0ff43e1',
    messagingSenderId: '468049593524',
    projectId: 'se7ety-a123',
    storageBucket: 'se7ety-a123.firebasestorage.app',
    iosBundleId: 'com.example.se7ety123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJc7gibHVMhyUi_RPdQvmSZA7snUD4jdw',
    appId: '1:468049593524:ios:603e6668cc3a35d0ff43e1',
    messagingSenderId: '468049593524',
    projectId: 'se7ety-a123',
    storageBucket: 'se7ety-a123.firebasestorage.app',
    iosBundleId: 'com.example.se7ety123',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdq1iB-rHNEQeiTJ-VKU0_W0nELAfqCEQ',
    appId: '1:468049593524:web:27dd6e9fbaba77e7ff43e1',
    messagingSenderId: '468049593524',
    projectId: 'se7ety-a123',
    authDomain: 'se7ety-a123.firebaseapp.com',
    storageBucket: 'se7ety-a123.firebasestorage.app',
    measurementId: 'G-RJMMN8TZPQ',
  );
}
